





export const products = [
  {

    title: 'AirStride X-50',
    brand: 'adidas',
    size: ['s40','s41','s42'],
    price: 169.00,
    shortdisc: 'The AirStride X-50 is designed for ultimate comfort and performance, featuring advanced cushioning technology and a sleek design.',
    disc: 'Step up your style and performance with the all-new AirStride X-50 sneakers. Crafted with precision and designed for maximum comfort, this pair is ideal for daily wear, gym sessions, or casual outings. The breathable mesh upper keeps your feet cool, while the cushioned sole absorbs every step with ease. Whether youre running errands or making a fashion statement, the AirStride X-50 delivers both function and fashion.',
    highlights: [
      "Lightweight Design: Engineered to reduce fatigue for all-day comfort.",
      "Breathable Mesh Upper: Keeps your feet dry and cool, even in hot weather.",
      "Shock-Absorbing Sole: Provides great cushioning for long walks or workouts.",
      "Sleek & Modern Look: Pairs perfectly with jeans, joggers, or sportswear.",
      "Multiple Color Options: Choose from bold shades like red, black, green, and blue.",
      "Available Sizes: From EU 38 to 45 (US 6 to 11.5).",
      "Easy to Clean: Wipe with a damp cloth to keep them looking fresh."
    ],
    rate: 4.5,
    Category: [ 'Sports'],
    img: 'adidas',
    id : "7a8f9b6e-ec34-42f6-93bd-2a3b5a1e6f9a",
  },
  {
    title: 'VoltEdge Runner Pro',
    brand: 'nike',
    size: ['s41','s42'],
    price: 80.00,
    shortdisc: 'The VoltEdge Runner Pro offers dynamic performance and a lightweight frame perfect for daily runners.',
    disc: 'Designed for high-energy runners and urban explorers, the VoltEdge Runner Pro combines advanced cushioning with bold aesthetics.',
    highlights: [
      "Featherweight Design: Reduces strain during long sessions.",
      "Knit Upper: Enhances airflow and flexibility.",
      "Responsive Bounce Tech: Propels your steps forward.",
      "Breathable Mesh Upper: Keeps your feet dry and cool, even in hot weather.",
      "Shock-Absorbing Sole: Provides great cushioning for long walks or workouts.",
      "Reflective Strips: Boosts visibility in low light.",
      "Ergonomic Heel Cup: Cradles the heel for added support."
    ],
    rate: 4.3,
    Category: ['modern', 'sports'],
    img: 'colorshoe',
    id :  "c41dbed7-4a7c-4fd4-b073-67ae30ff72cf",
  },
  {
    title: 'NimbusFlex 360',
    brand: 'puma',
    size: ['s38','s39','s40'],
    price: 64.00,
    shortdisc: 'Experience superior flexibility and speed with NimbusFlex 360s adaptive fit and cloud-like sole.',
    disc: 'Unleash flexibility and speed with the NimbusFlex 360 trainers, engineered for athletes who demand agility.',
    highlights: [
      "Zone Grip Outsole: Great traction across surfaces.",
      "Adaptive Fit Mesh: Comfortably hugs your feet.",
      "Ultra-Flex Sole: Promotes a natural gait cycle.",
      "Impact Shield Cushioning: Softens landings on all terrain.",
      "Quick-Dry Lining: Keeps feet dry during intense sessions.",
      "Streamlined Profile: Built for agile movements.",
      "Heel Stability Pad: Enhances balance and control."
    ],
    rate: 4.7,
    Category: ['classy'],
    img: 'bal',
    id : "bcb3ee2a-4e14-4635-8fd9-6d2c5f4d0d75",
  },
  {
    title: 'UrbanTrack Evo',
    brand: 'converce',
    size: ['s38','s39','s40'],
    price: 173.00,
    shortdisc: 'UrbanTrack Evo combines bold urban style with rugged construction built for daily wear.',
    disc: 'Level up your streetwear game with UrbanTrack Evo sneakers. These shoes fuse rugged style with modern functionality.',
    highlights: [
      "Anti-Slip Sole: Maintains traction on smooth streets.",
      "Urban-Ready Build: Durable enough for city exploration.",
      "Subtle Branding: Sleek look with minimal distractions.",
      "High-Abrasion Rubber: Increases outsole longevity.",
      "Contoured Footbed: Adapts to foot shape.",
      "Reinforced Stitching: Withstands daily wear and tear.",
      "Shock Diffusion Heel: Eases pressure with every step."
    ],
    rate: 4.2,
    Category: ['Streetwear', 'modern', 'Casual'],
    img: 'starshoe',
    id : "53c1743d-bdf2-4a26-a66d-c94ce93230b5",
  },
  {
    title: 'ZenCore Flow',
    brand: 'reebok',
    size: ['s37','s38','s39'],
    price: 95.00,
    shortdisc: 'ZenCore Flow is your go-to for minimalist comfort whether at home, gym, or out and about.',
    disc: 'The ZenCore Flow shoes are perfect for those who love minimalist fashion without sacrificing comfort.',
    highlights: [
      "Slip-On Fit: Quick and easy to wear.",
      "CushionCore Footbed: Maximum softness.",
      "Sleek Silhouette: Minimalist and stylish.",
      "Flexible Sole: Supports a range of motion.",
      "Breathable Liner: Keeps feet fresh all day.",
      "Arch-Support Band: Gentle stability boost.",
      "Foldable Design: Packs flat for travel ease."
    ],
    rate: 4.6,
    Category: [ 'classy'],
    img: 'talon',
    id : "de09473c-0552-4fd3-8ba3-63c3601e6220",
  },
  {
    title: 'StratoMax Trail',
    brand: 'puma',
    size: ['s39','s40','s42'],
    price: 40.00,
    shortdisc: 'StratoMax Trail Runner is made for outdoor explorers with enhanced traction and weather resistance.',
    disc: 'Conquer rugged paths with the StratoMax Trail Runner. These shoes are designed for hikers, trail runners, and adventurers.',
    highlights: [
      "TrailGrip Outsole: Superior grip on uneven terrain.",
      "WeatherGuard Exterior: Resists rain and mud.",
      "Ankle Lock Support: Prevents twists and injuries.",
      "MudGuard Toe Cap: Protection against dirt and debris.",
      "Secure Lace System: Stays tied on rugged paths.",
      "Padded Collar: Comfort around the ankles.",
      "Reflective Overlays: Improves visibility in nature."
    ],
    rate: 4.4,
    Category: ['classic', 'Hiking', 'sports'],
    img: 'puma',
    id : "2cbcf842-45a5-4be1-a879-b8b98d2f6174",
  },
  {
    title: 'PulseNova Glide',
    brand:'nike',
    size: ['s41','s42'],
    price: 240.00,
    shortdisc: 'PulseNova Glide boosts your stride with responsive energy return and futuristic design.',
    disc: 'With its futuristic look and premium cushioning, the PulseNova Glide is made for speed lovers and urban style enthusiasts.',
    highlights: [
      "EnergyReturn Midsole: Launches you forward.",
      "Seamless Upper: No chafing or discomfort.",
      "Reflective Trim: Enhances night visibility.",
      "Toe Flex Panel: Boosts push-off dynamics.",
      "Adaptive Heel Cradle: Keeps foot in place.",
      "Sculpted Outsole: Designed for speed.",
      "Ultra-Light Build: Barely there feel."
    ],
    rate: 4.8,
    Category: ['Performance', 'sports', 'modern'],
    img: 'colorshoe',
    id : "b7b6d2f3-6c6a-4e11-b6a4-05d20a6f1a44",
  },
  {
    title: 'TerraCore Element',
    brand:'converce',
    size: ['s37','s38'],
    price: 100.00,
    shortdisc: 'TerraCore Element blends eco-conscious materials with breathable design and all-day comfort.',
    disc: 'Inspired by nature, the TerraCore Element combines earthy tones with eco-friendly materials.',
    highlights: [
      "Recycled Knit Upper: Breathable and green.",
      "Natural Dye Colors: Safe and stylish.",
      "EcoFoam Sole: Soft and sustainable.",
      "Organic Cotton Laces: Environmentally friendly.",
      "Vegan Construction: No animal products used.",
      "Durable Outsole: Designed to last longer.",
      "Lightweight Fabrication: Reduces foot fatigue."
    ],
    rate: 4.5,
    Category: ['Eco-Friendly', 'Sustainable', 'classy'],
    img: 'starshoe',
    id : "5d1f91a5-b0b7-42e2-b3db-157a3160ad0c",

  },
  {
    title: 'Ignite AeroCharge',
    brand:'adidas',
    size: ['s42'],
    price: 135.00,
    shortdisc: 'Ignite AeroCharge is a performance beast, combining speed-enhancing sole with stylish details.',
    disc: 'Accelerate your movement with the Ignite AeroCharge. Designed for sprinters and fitness buffs.',
    highlights: [
      "DualDensity Foam: Maximum shock absorption.",
      "BreathLock Upper: Keeps feet ventilated.",
      "HeelTab Pull: Easy wear-on action.",
      "Dynamic Arch Plate: Enhances propulsion.",
      "Low-Profile Tongue: Adds flexibility.",
      "Rebound Forefoot: Boosts lift-off phase.",
      "Grippy Traction Nodes: Keep you grounded."
    ],
    rate: 4.3,
    Category: ['Sprint', 'Athletic', 'sports'],
    img: 'adidas',
    id : "99382377-bc9c-44e4-b2cd-6d88eb3a404e",
  },
  {
    title: 'FlexCore Adapt',
    brand:'puma',
    size: ['s40','s41'],
    price: 46.00,
    shortdisc: 'FlexCore Adapt suits any environment with its flexible midsole and lightweight construction.',
    disc: 'For those who demand versatility, the FlexCore Adapt transitions effortlessly from home to street to gym.',
    highlights: [
      "360 Flex Channels: Freedom of movement.",
      "BreathEasy Upper: Ventilated for comfort.",
      "Style+Function: Matches any outfit.",
      "Elastic Arch Wrap: Enhances support.",
      "GripZone Outsole: Prevents slips.",
      "Quick-Dry Footbed: Keeps interior fresh.",
      "Reinforced Heel Pad: Absorbs heavy landings."
    ],
    rate: 4.6,
    Category: ['sports', 'CrossFit', 'Daily Wear'],
    img: 'puma',
    id : "ff176ebe-f05e-4623-8d15-708a1df3151e",

  },
    {
    title: 'SkyBlaze Runner',
    brand:'reebok',
    size: ['s38','s39'],
    price: 105.41,
    shortdisc: 'Built for explosive movement with precision grip and lightweight materials.',
    disc: 'Experience cutting-edge design and advanced performance in this versatile shoe, made for athletes and casual users alike.',
    highlights: ['GripMax Outsole: Unmatched traction on any terrain.', 'PowerFoam Midsole: Absorbs shock and returns energy.', 'FlexWave Technology: Promotes fluid, natural strides.', 'DualMesh Panels: Combine durability with ventilation.', 'FoamLite Base: Lightweight without compromising stability.', 'CoolBreeze Mesh: Enhances airflow during movement.', 'HydroShield Layer: Guards against moisture and splashes.'],
    rate: 4.6,
    Category: ['Training', 'classic', 'classy'],
    img: 'bligha',
    id:  "851e8c34-2c0b-4f40-9154-01b676d1f6c4",
  },
  {
    title: 'EchoStride X1',
    brand:'nike',
    size: ['s41'],

    price: 95.55,
    shortdisc: 'Engineered for long-distance runners looking for reliable cushioning and speed.',
    disc: 'Step confidently into your routine with a trainer that supports your every move, indoors or out.',
    highlights: ['EcoBlend Fabric', 'MotionGuard Heel', 'DualMesh Panels', 'ImpactZone Cushion', 'CloudStep Cushion', 'NightGlow Trim', 'FlexWave Technology'],
    rate: 4.4,
    Category: ['classic', 'Weatherproof', 'Explorer'],
    img: 'colorshoe',
    id:  "3f2f6a9f-4e4c-4d10-8e77-4f0a9d20f0f6",
  },
  {
    title: 'PhantomGrip Pro',
    brand:'puma',
    size: ['s37'],
    price: 124.00,
    shortdisc: 'Combines advanced outsole grip with breathable upper mesh for active users.',
    disc: "Featuring dynamic traction and breathable materials, it's built to move with you, wherever you go.",
    highlights: ['MotionGuard Heel', 'EcoBlend Fabric', 'FlexWave Technology', 'PowerFoam Midsole', 'QuickLace System', 'ErgoFit Insole', 'NightGlow Trim'],
    rate: 4.7,
    Category: ['sports', 'Streetwear', 'modern'],
    img: 'puma',
    id: "a46b8073-9ff9-43f4-8f8c-f3dcb937d789",
  },
];

