import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Myfooter from "./components/Myfooter";

import Header from "./components/Header";


import { ProductsProvider } from "./context/productList";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata = {

  description: "Generated by create next app",
    title: 'My E-Commerce',
    icons: {
  icon: "/favicon.ico",
}


};

export default function RootLayout({ children }) {





  return (
    <html lang="en">
      <body>
        <ProductsProvider>
                  <Header/>
        <div style={{height:'70px'}}></div>
        {children}
        <Myfooter/>
        </ProductsProvider>
      </body>
    </html>
  );
}
